/**
 * Comprehensive Course Meanings & Academic Disciplines Directory
 * Federal University of Agriculture, Abeokuta (FUNAAB)
 * 
 * Provides human-readable course titles, department explanations,
 * and practical descriptors for freshers and student leaders.
 */

import { VERIFIED_COURSE_TITLES } from '../data/timetable';
import { getRootCourseCode } from './scheduleLogic';

export const COURSE_PREFIX_DISCIPLINES: Record<string, string> = {
  AAD: 'Agricultural Administration',
  ABE: 'Agricultural & Bio-Resources Engineering',
  ABG: 'Animal Breeding & Genetics',
  ACC: 'Accounting',
  AEM: 'Agribusiness & Farm Management',
  AER: 'Agricultural Economics & Farm Management',
  AGE: 'Agricultural Economics',
  AGR: 'General Agriculture',
  AGX: 'Agricultural Communication & Extension',
  ANA: 'Agricultural Economics & Agribusiness',
  ANN: 'Animal Nutrition',
  ANP: 'Animal Physiology',
  ANS: 'Animal Science',
  APH: 'Animal Production & Health',
  ARD: 'Agricultural & Rural Development',
  BAM: 'Business Administration',
  BCH: 'Biochemistry',
  BFN: 'Banking & Finance',
  BIO: 'General Biology',
  BOT: 'Pure & Applied Botany',
  BUA: 'Business Administration',
  CBS: 'Computing & Basic Sciences',
  CEE: 'Civil Engineering',
  CHM: 'Pure & Applied Chemistry',
  CLT: 'Clothing & Textiles',
  CMS: 'Computing & Mathematical Sciences',
  COS: 'Computer Science',
  CPS: 'Crop Production & Protection',
  CPT: 'Crop Protection',
  CRD: 'Crop Production & Rural Development',
  CSA: 'Computer Science Applications',
  CSC: 'Computer Science',
  CVE: 'Civil Engineering',
  CYB: 'Cyber Security',
  DES: 'Developmental Economics & Studies',
  DTS: 'Data Science',
  ECO: 'Economics',
  EEE: 'Electrical & Electronics Engineering',
  ELE: 'Electrical & Electronics Engineering',
  EMT: 'Environmental Management & Toxicology',
  ENT: 'Entrepreneurship',
  ETS: 'Entrepreneurial Studies',
  FAA: 'Fine & Applied Arts',
  FCS: 'Family & Consumer Studies',
  FIN: 'Banking & Finance',
  FIS: 'Aquaculture & Fisheries Management',
  FRM: 'Forestry & Wildlife Management',
  FST: 'Food Science & Technology',
  FWM: 'Forestry & Wildlife Management',
  FWP: 'Forestry & Wood Processing',
  GET: 'General Engineering & Technology',
  GEY: 'Geology',
  GLR: 'General Engineering Technology',
  GLY: 'Geology & Mineral Resources',
  GNS: 'General Studies',
  GST: 'General Studies Programme',
  HLM: 'Health & Life Management',
  HRT: 'Horticulture',
  HSM: 'Home Science & Management',
  HTM: 'Hospitality & Tourism Management',
  HWM: 'Hydrology & Water Resources Management',
  ICH: 'Industrial Chemistry',
  ICT: 'Information & Communication Technology',
  IFT: 'Information Technology',
  INS: 'Information Systems',
  LIS: 'Library & Information Science',
  MCB: 'Microbiology',
  MCE: 'Mechanical Engineering',
  MEE: 'Mechanical Engineering',
  MGS: 'Management Studies',
  MTE: 'Mechatronics Engineering',
  MTH: 'Mathematics',
  MTS: 'Mathematical Sciences & Calculus',
  NTD: 'Nutrition & Dietetics',
  NUT: 'Nutrition & Dietetics',
  PBS: 'Plant Breeding & Seed Technology',
  PBST: 'Plant Breeding & Seed Technology',
  PCP: 'Plant Physiology & Crop Production',
  PHS: 'General Physics & Physical Sciences',
  PHY: 'General Physics',
  PRM: 'Pasture & Range Management',
  SEN: 'Software Engineering',
  SOS: 'Soil Science & Land Management',
  STA: 'Statistics',
  STS: 'Statistics',
  VBA: 'Veterinary Anatomy',
  VBB: 'Veterinary Biochemistry',
  VBM: 'Veterinary Microbiology',
  VBP: 'Veterinary Physiology & Pharmacology',
  VCC: 'Veterinary Clinical Practice',
  VCH: 'Veterinary Public Health',
  VCM: 'Veterinary Medicine',
  VCS: 'Veterinary Surgery',
  VHM: 'Veterinary Public Health & Preventive Medicine',
  VMD: 'Veterinary Medicine',
  VPC: 'Veterinary Pathology',
  VPM: 'Veterinary Parasitology & Entomology',
  VPR: 'Veterinary Reproduction & Theriogenology',
  VPT: 'Veterinary Pathology',
  VPY: 'Veterinary Physiology',
  WMA: 'Water Resources Management & Agrometeorology',
  WRM: 'Wildlife & Range Management',
  WSH: 'Watershed & Environmental Hydrology',
  ZOO: 'Pure & Applied Zoology',
  SPORTS: 'Official University Sports & Inter-Hall Games',
};

export const EXTENDED_COURSE_TITLES: Record<string, string> = {
  // General 100L Courses
  'MTS 101': 'Elementary Mathematics I (Algebra & Trigonometry)',
  'MTS 103': 'Elementary Mathematics II (Vectors & Geometry)',
  'MTS 105': 'Algebra & Calculus for Sciences & Computing',
  'MTS 201': 'Mathematical Methods I',
  'MTS 203': 'Advanced Calculus & Ordinary Differential Equations',
  'MTS 211': 'Abstract Algebra I',
  'MTS 223': 'Numerical Analysis I',
  'MTS 241': 'Mathematical Methods I',
  'MTS 301': 'Complex Analysis',
  'MTS 341': 'Discrete Mathematics & Linear Algebra',
  'MTS 351': 'Real Analysis',
  'MTS 361': 'Partial Differential Equations',
  'MTS 421': 'Ordinary Differential Equations II',
  'MTS 423': 'Optimization Theory',
  'MTS 453': 'Functional Analysis',
  'MTS 461': 'Fluid Dynamics',
  'MTS 463': 'Analytical Dynamics',

  // Physics
  'PHS 101': 'General Physics I (Mechanics, Thermal & Waves)',
  'PHY 101': 'General Physics I (Mechanics, Thermal & Waves)',
  'PHS 103': 'General Physics II (Sound, Optics & Magnetism)',
  'PHY 103': 'General Physics II (Electricity & Magnetism)',
  'PHS 105': 'Physics for Biological Sciences',
  'PHY 105': 'Physics for Agricultural & Medical Sciences',
  'PHS 191': 'General Physics Practical Laboratory I',
  'PHY 107': 'General Physics Practical Laboratory I',
  'PHS 245': 'Thermal Physics',
  'PHS 251': 'Waves and Optics',
  'PHS 291': 'Intermediate Physics Practical Laboratory',
  'PHY 201': 'Modern Physics',
  'PHY 205': 'Vibrations and Waves',
  'PHY 207': 'Experimental Physics Practical',
  'PHY 211': 'Electromagnetism',
  'PHS 311': 'Electromagnetic Theory I',
  'PHS 341': 'Quantum Physics I',
  'PHS 383': 'Electronics I',
  'PHS 391': 'Advanced Physics Practical Laboratory',
  'PHS 411': 'Solid State Physics',
  'PHS 471': 'Atomic & Nuclear Physics',
  'PHS 473': 'Statistical Mechanics',
  'PHS 491': 'Senior Physics Practical Laboratory',

  // Chemistry
  'CHM 101': 'General Chemistry I (Inorganic & Physical)',
  'CHM 103': 'General Chemistry II (Organic Chemistry)',
  'CHM 107': 'General Chemistry Practical Laboratory',
  'CHM 191': 'General Chemistry Practical Laboratory I',
  'CHM 207': 'Organic Chemistry I',
  'CHM 211': 'Inorganic Chemistry I',
  'CHM 213': 'Analytical Chemistry I',
  'CHM 221': 'Physical Chemistry I',
  'CHM 231': 'Environmental Chemistry',
  'CHM 243': 'Applied Chemistry',
  'CHM 265': 'Basic Industrial Chemistry',
  'CHM 269': 'Petrochemical Technology',
  'CHM 293': 'Practical Chemistry Laboratory II',
  'CHM 299': 'Chemical Processing Workshop',
  'CHM 301': 'Inorganic Chemistry II',
  'CHM 303': 'Organic Chemistry II',
  'CHM 309': 'Physical Chemistry II',
  'CHM 311': 'Instrumental Methods of Analysis',
  'CHM 313': 'Chemical Kinetics & Dynamics',
  'CHM 333': 'Quantum Chemistry',
  'CHM 391': 'Experimental Chemistry Laboratory III',
  'CHM 395': 'Practical Physical Chemistry',
  'CHM 401': 'Coordination Chemistry',
  'CHM 403': 'Reaction Mechanisms in Organic Chemistry',
  'CHM 407': 'Polymer Chemistry',
  'CHM 409': 'Advanced Analytical Chemistry',
  'CHM 411': 'Statistical Thermodynamics',
  'CHM 413': 'Heterocyclic Chemistry',
  'CHM 421': 'Spectroscopy & Molecular Structure',
  'CHM 425': 'Natural Products Chemistry',
  'CHM 431': 'Chemical Crystallography',
  'CHM 433': 'Surface & Colloid Chemistry',
  'CHM 443': 'Electrochemistry',
  'CHM 491': 'Senior Chemistry Research Project & Practicals',

  // Biological Sciences
  'BIO 101': 'General Biology I (Cell Biology & Diversity)',
  'BIO 103': 'General Biology II (Plant & Animal Systems)',
  'BIO 105': 'Introductory Botany',
  'BIO 107': 'General Biology Practical Laboratory I',
  'BIO 191': 'General Biology Practical Laboratory I',
  'BIO 201': 'General Ecology & Fieldwork',
  'BIO 203': 'Cell Biology & Genetics',
  'BOT 105': 'Plant Diversity & Cryptogamic Botany',
  'BOT 201': 'Plant Anatomy & Morphology',
  'BOT 203': 'Seed Plants Morphology & Taxonomy',
  'BOT 211': 'Plant Physiology I',
  'BOT 215': 'Plant Systematics',
  'BOT 301': 'Plant Pathology',
  'BOT 303': 'Plant Physiology II',
  'BOT 323': 'Mycology & Lichenology',
  'BOT 325': 'Plant Anatomy Laboratory',
  'BOT 327': 'Bryology and Pteridology',
  'BOT 329': 'Plant Genetics',
  'BOT 331': 'Economic Botany',
  'BOT 403': 'Plant Biotechnology',
  'BOT 405': 'Plant Breeding',
  'BOT 407': 'Medicinal Plants',
  'BOT 411': 'Plant Molecular Biology',
  'ZOO 101': 'Lower Invertebrates & General Zoology',
  'ZOO 201': 'Invertebrate Zoology II',
  'ZOO 203': 'Chordate Zoology & Comparative Anatomy',
  'ZOO 211': 'Animal Ecology',
  'ZOO 261': 'Vertebrate Zoology Practical',
  'ZOO 309': 'Animal Histology & Cytology',
  'ZOO 365': 'Applied Entomology',
  'ZOO 367': 'Parasitology & Vector Biology',
  'ZOO 369': 'Parasitology Laboratory Practical',
  'ZOO 411': 'Mammalian Physiology',
  'ZOO 461': 'Applied Animal Behaviour',
  'ZOO 463': 'Fisheries Biology',
  'ZOO 467': 'Evolution and Biosystematics',
  'ZOO 469': 'Immunobiology',
  'ZOO 473': 'Environmental Toxicology',

  // Microbiology & Biochemistry
  'MCB 111': 'Introductory Microbiology & Laboratory Methods',
  'MCB 201': 'General Microbiology I',
  'MCB 207': 'Microbial Physiology and Metabolism',
  'MCB 231': 'General Microbiology II',
  'MCB 301': 'Bacteriology',
  'MCB 303': 'Mycology',
  'MCB 305': 'Microbiology Laboratory Practicals',
  'MCB 309': 'Immunology & Immunochemistry',
  'MCB 325': 'Microbial Genetics',
  'MCB 401': 'Pathogenic Microbiology',
  'MCB 403': 'Industrial Microbiology',
  'MCB 405': 'Environmental Microbiology',
  'MCB 407': 'Virology',
  'MCB 411': 'Food Microbiology',
  'BCH 201': 'General Biochemistry I',
  'BCH 203': 'Chemistry of Biomolecules',
  'BCH 301': 'Enzymology',
  'BCH 307': 'Metabolism of Carbohydrates & Lipids',
  'BCH 309': 'Metabolism of Amino Acids & Nucleic Acids',
  'BCH 311': 'Bioenergetics & Biological Oxidation',
  'BCH 323': 'Biochemical Methods & Instrumentation',
  'BCH 401': 'Advanced Enzymology',
  'BCH 403': 'Molecular Biology & Genetic Engineering',
  'BCH 407': 'Biochemical Pharmacology & Toxicology',
  'BCH 409': 'Clinical Biochemistry',
  'BCH 413': 'Industrial Biochemistry & Biotechnology',
  'BCH 417': 'Plant Biochemistry',
  'BCH 423': 'Membrane Biochemistry',
  'BCH 429': 'Senior Biochemistry Laboratory Project',
  'BCH 433': 'Immunobiochemistry',

  // Engineering Core (COLENG)
  'GET 101': 'Engineer in Society & Technology',
  'GET 201': 'Applied Electricity & Electronics',
  'GET 203': 'Engineering Mechanics I (Statics)',
  'GET 205': 'Fundamentals of Fluid Mechanics',
  'GET 207': 'General Engineering Materials',
  'GET 209': 'Engineering Mathematics I',
  'GET 211': 'Computer Programming for Engineers',
  'MCE 101': 'Engineering Drawing I',
  'MCE 103': 'Workshop Practice I',
  'MCE 107': 'Mechanical Engineering Orientation',
  'MCE 201': 'Engineering Mechanics I',
  'MCE 205': 'Fluid Mechanics I',
  'MCE 301': 'Thermodynamics I',
  'MCE 313': 'Mechanics of Machines I',
  'MCE 323': 'Strength of Materials I',
  'MCE 325': 'Machine Drawing & CAD',
  'MCE 341': 'Applied Thermodynamics',
  'MCE 387': 'Mechanical Engineering Laboratory I',
  'MCE 401': 'Heat and Mass Transfer',
  'MCE 403': 'Design of Machine Elements',
  'MCE 405': 'Fluid Power & Machinery',
  'MCE 409': 'Mechanical Engineering Laboratory II',
  'MCE 411': 'Manufacturing Technology',
  'MCE 413': 'Control Systems Engineering',
  'MCE 415': 'Automotive Engineering',
  'MCE 417': 'Refrigeration and Air Conditioning',
  'MCE 419': 'Engineering Metallurgy',
  'MCE 421': 'Engineering Measurements & Instrumentation',
  'MCE 425': 'CAD/CAM Laboratory Practicals',
  'MCE 487': 'Mechanical Laboratory Practicals III',
  'MCE 501': 'Advanced Thermodynamics',
  'MCE 503': 'Tribology and Lubrication',
  'MCE 509': 'Power Plant Engineering',
  'MCE 513': 'Vibrations and Acoustics',
  'MCE 515': 'Renewable Energy Systems',
  'MCE 517': 'Computational Fluid Dynamics',
  'MCE 527': 'Operations Management in Engineering',
  'MCE 587': 'Senior Mechanical Engineering Project Laboratory',
  'CVE 201': 'Engineer in Society & Civil Infrastructure',
  'CVE 301': 'Strength of Materials & Structural Analysis',
  'CVE 303': 'Civil Engineering Drawing & Surveying',
  'CVE 305': 'Civil Engineering Laboratory Practicals I',
  'CVE 309': 'Fluid Mechanics for Civil Engineers',
  'CVE 311': 'Engineering Surveying Fieldwork',
  'CVE 321': 'Highway & Transportation Engineering I',
  'CVE 401': 'Reinforced Concrete Design I',
  'CVE 409': 'Civil Engineering Laboratory Practicals II',
  'CVE 415': 'Structural Analysis II',
  'CVE 417': 'Soil Mechanics and Foundation Engineering',
  'CVE 425': 'Hydrology & Water Resources Engineering',
  'CVE 501': 'Design of Steel and Timber Structures',
  'CVE 505': 'Civil Engineering Studio Practice',
  'CVE 511': 'Advanced Foundation Engineering',
  'CVE 513': 'Environmental & Public Health Engineering',
  'CVE 515': 'Highway Materials & Pavement Design',
  'CVE 519': 'Bridge Engineering & Construction',
  'CVE 523': 'Water Supply & Wastewater Treatment',
  'CVE 525': 'Civil Engineering Construction Project Management',
  'ELE 201': 'Applied Electricity I',
  'ELE 291': 'Electrical Engineering Laboratory Practicals I',
  'ELE 301': 'Direct Current & Alternating Current Machines',
  'ELE 305': 'Physical Electronics & Solid State Devices',
  'ELE 309': 'Analogue Electronics',
  'ELE 311': 'Circuit Theory I',
  'ELE 391': 'Electrical & Electronics Laboratory Practicals II',
  'ELE 393': 'Electrical Machines Laboratory',
  'ELE 401': 'Control Engineering I',
  'ELE 403': 'Electrical Power Systems I',
  'ELE 405': 'Telecommunication Principles',
  'ELE 491': 'Advanced Electrical Engineering Laboratory',
  'ELE 493': 'Power Systems Practicals',
  'ELE 503': 'Power Systems Analysis & Stability',
  'ELE 507': 'Digital Signal Processing',
  'ELE 509': 'Microprocessor Systems & Applications',
  'ELE 513': 'Electrical Machine Design',
  'ELE 515': 'High Voltage Engineering',
  'ELE 525': 'Telecommunication Switching Systems',
  'ABE 101': 'Introduction to Agricultural Engineering',
  'ABE 201': 'Fundamentals of Bio-Resources Engineering',
  'ABE 223': 'Farm Power and Machinery Principles',
  'ABE 301': 'Agricultural Power & Tractors',
  'ABE 303': 'Farm Structures and Environmental Control',
  'ABE 321': 'Agricultural Materials Handling',
  'ABE 401': 'Irrigation & Drainage Engineering',
  'ABE 403': 'Soil & Water Conservation Engineering',
  'ABE 405': 'Farm Power Machinery Design Laboratory',
  'ABE 407': 'Agricultural Processing Engineering Practicals',
  'ABE 413': 'Post-Harvest Technology',
  'ABE 415': 'Rural Water Supply and Sanitation',
  'ABE 443': 'Agricultural Land Clearing & Development',
  'ABE 501': 'Farm Power Machinery Testing & Evaluation',
  'ABE 505': 'Advanced Irrigation System Design',
  'ABE 513': 'Storage Engineering of Farm Products',
  'ABE 515': 'Bio-Energy Systems Engineering',
  'ABE 517': 'Agricultural Engineering Laboratory Research',
  'ABE 519': 'Food Process Plant Design',
  'ABE 521': 'Environmental Engineering in Agriculture',
  'ABE 525': 'Agricultural Waste Management & Recycling',
  'ABE 535': 'Instrumentation in Agricultural Engineering',
  'MTE 401': 'Mechatronics System Design & Modeling',
  'MTE 403': 'Microcontrollers & Embedded Systems',
  'MTE 407': 'Sensors, Actuators & Signal Conditioning',
  'MTE 501': 'Robotics & Autonomous Systems',
  'MTE 503': 'Industrial Automation & PLC',
  'MTE 509': 'Mechatronics Laboratory Practicals',
  'MTE 511': 'Artificial Intelligence in Mechatronics',
  'MTE 523': 'Advanced CNC & Precision Machine Tools',

  // Agriculture & Animal Science (COLANIM & COLPLANT)
  'ANS 101': 'Principles of Animal Production',
  'ANS 103': 'Introductory Animal Science',
  'ANS 107': 'Livestock Breeds & Farm Animal Management',
  'ANS 201': 'Anatomy & Physiology of Farm Animals',
  'ANS 241': 'Introduction to Animal Agriculture',
  'ANS 303': 'Monogastric Animal Nutrition',
  'AGR 201': 'General Agriculture I (Crop & Soil Sciences)',
  'AGR 203': 'General Agriculture II (Animal & Forestry Sciences)',
  'AGX 101': 'Introduction to Agricultural Communication',
  'AGX 113': 'Rural Sociology & Community Extension',
  'ABG 311': 'Principles of Animal Genetics',
  'ABG 501': 'Animal Breeding Practical Laboratory',
  'ABG 505': 'Molecular Genetics in Livestock',
  'ABG 507': 'Population Genetics in Animals',
  'ABG 509': 'Applied Animal Breeding',
  'ANN 303': 'Principles of Animal Nutrition',
  'ANN 313': 'Feeds and Feeding Stuffs',
  'ANN 501': 'Ruminant Animal Nutrition',
  'ANN 505': 'Feed Mill Technology & Quality Control',
  'ANN 509': 'Applied Animal Nutrition Laboratory',
  'ANN 513': 'Non-Ruminant Animal Nutrition',
  'ANN 517': 'Nutritional Toxicology in Farm Animals',
  'ANP 101': 'Introductory Animal Physiology',
  'ANP 201': 'Animal Physiology & Reproduction',
  'ANP 211': 'Endocrinology of Farm Animals',
  'ANP 501': 'Reproductive Physiology in Livestock',
  'ANP 503': 'Lactation & Growth Physiology',
  'ANP 505': 'Environmental Physiology & Animal Welfare',
  'ANP 507': 'Physiology of Adaptation in Animals',
  'ANP 509': 'Animal Neurophysiology',
  'APH 311': 'Poultry Production & Hatchery Management',
  'APH 501': 'Cattle, Sheep & Goat Production',
  'APH 503': 'Swine and Rabbit Production Management',
  'APH 505': 'Hatchery Management & Avian Health Practicals',
  'APH 509': 'Dairy Cattle Management & Processing',
  'PCP 101': 'Introductory Crop Production',
  'PCP 191': 'Introductory Crop Production Practical',
  'PCP 201': 'Principles of Crop Production',
  'PCP 211': 'Principles of Weed Science',
  'PCP 301': 'Field Crop Production',
  'PCP 311': 'Tree and Plantation Crops',
  'PCP 501': 'Crop Physiology and Yield Potential',
  'PCP 503': 'Plant Nutrition and Soil Fertility Practicals',
  'PCP 505': 'Weed Ecology & Integrated Management',
  'PCP 507': 'Post-Harvest Physiology of Crops',
  'CPT 503': 'Insect Pest Management',
  'CPT 507': 'Plant Nematology & Bacteriology Practicals',
  'CPT 509': 'Plant Virology & Disease Diagnosis Laboratory',
  'CPT 511': 'Pesticide Application & Plant Clinic',
  'CPT 515': 'Post-Harvest Crop Protection',
  'CRD 105': 'Principles of Agricultural Cooperatives',
  'CRD 201': 'Cooperative Economics & Accounting',
  'CRD 203': 'Rural Development Cooperatives',
  'HRT 301': 'Principles of Horticulture',
  'HRT 501': 'Fruit and Vegetable Crop Production',
  'HRT 503': 'Floriculture & Ornamental Landscaping',
  'HRT 507': 'Plant Nursery Management Practicals',
  'HRT 509': 'Post-Harvest Handling of Horticultural Crops',
  'PBS 501': 'Principles of Plant Breeding',
  'PBS 505': 'Seed Science and Technology',
  'PBS 507': 'Hybrid Seed Production & Certification',
  'PBS 509': 'Cytogenetics & Mutation Breeding',
  'SOS 101': 'Introduction to Soil Science',
  'SOS 211': 'Principles of Soil Science',
  'SOS 513': 'Soil Fertility and Plant Nutrition',
  'SOS 515': 'Soil Survey and Land Evaluation',
  'SOS 517': 'Soil Physics & Conservation',
  'SOS 519': 'Soil Microbiology & Biochemistry',
  'PRM 501': 'Forage Production & Pasture Agronomy',
  'PRM 503': 'Range Ecology & Grazing Management',
  'PRM 505': 'Pasture Conservation & Seed Technology',

  // Management Sciences (COLENDS)
  'ACC 101': 'Principles of Accounting I',
  'ACC 203': 'Cost Accounting I',
  'ACC 205': 'Management Accounting',
  'ACC 207': 'Principles of Auditing',
  'ACC 209': 'Financial Accounting I',
  'ACC 211': 'Introduction to Taxation',
  'ACC 301': 'Advanced Financial Accounting I',
  'ACC 313': 'Cost Accounting II',
  'ACC 315': 'Auditing Principles and Investigation',
  'ACC 317': 'Public Sector Accounting',
  'ACC 401': 'Advanced Financial Accounting II',
  'ACC 407': 'International Accounting',
  'ACC 413': 'Auditing Practice and Assurance',
  'BAM 101': 'Introduction to Business Administration I',
  'BAM 205': 'Quantitative Methods in Business',
  'BAM 213': 'Business Communication',
  'BAM 215': 'Principles of Marketing',
  'BAM 303': 'Organizational Behaviour',
  'BAM 305': 'Human Resource Management',
  'BAM 401': 'Business Policy and Strategic Management I',
  'BAM 403': 'Corporate Finance',
  'BAM 405': 'Operations Research in Business',
  'BAM 409': 'Production & Operations Management',
  'BAM 413': 'Supply Chain Management',
  'BAM 417': 'International Business Management',
  'BFN 101': 'Elements of Banking & Finance',
  'BFN 203': 'Principles of Finance',
  'BFN 309': 'Money and Capital Markets',
  'BFN 313': 'Commercial Banking Operations',
  'BFN 315': 'Credit Management and Analysis',
  'BFN 401': 'Investment Analysis & Portfolio Management',
  'ECO 101': 'Principles of Economics I (Microeconomics)',
  'ECO 103': 'Introduction to Statistics for Economics',
  'ECO 201': 'Microeconomic Theory I',
  'ECO 203': 'Macroeconomic Theory I',
  'ECO 205': 'Mathematics for Economists I',
  'ECO 211': 'Economic History of Nigeria',
  'ECO 251': 'Introduction to Econometrics',
  'ECO 253': 'Macroeconomics Foundations',
  'ECO 255': 'Applied Mathematics in Economics',
  'ECO 301': 'Intermediate Microeconomics',
  'ECO 303': 'Intermediate Macroeconomics',
  'ECO 315': 'Public Sector Economics',
  'ECO 353': 'Economic Planning & Development',
  'ECO 355': 'Monetary Economics',
  'ECO 357': 'Labour Economics',
  'ECO 361': 'International Trade & Finance',
  'ECO 365': 'Agricultural Economics & Policy',
  'ECO 373': 'Environmental & Resource Economics',
  'ECO 401': 'Advanced Microeconomic Theory',
  'ECO 403': 'Advanced Macroeconomic Theory',
  'ECO 405': 'Applied Econometrics',
  'ECO 415': 'Development Economics',
  'ECO 451': 'International Economics',
  'ECO 453': 'Public Finance',
  'ECO 455': 'Project Evaluation and Appraisal',
  'ECO 459': 'Comparative Economic Systems',
  'ECO 465': 'Economic Model Building',
  'ETS 101': 'Introduction to Entrepreneurial Studies',
  'ETS 211': 'Business Creation & Opportunity Analysis',
  'ETS 301': 'Venture Creation & Capital Mobilization',
  'ETS 305': 'Entrepreneurial Marketing & Sales Strategy',
  'ETS 311': 'Social Entrepreneurship',
  'ETS 313': 'Small Business Financial Management',
  'ETS 401': 'Enterprise Planning & Feasibility Studies',
  'ETS 403': 'Corporate Entrepreneurship & Innovation',
  'ETS 405': 'Franchising & Business Expansion',
  'ETS 407': 'Technology Entrepreneurship',
  'ETS 413': 'Family Business Governance',
  'ETS 417': 'Ethics & Legal Aspects of Entrepreneurship',

  // Food Science & Human Ecology (COLFHEC)
  'FST 101': 'Introduction to Food Science & Technology',
  'FST 203': 'Introduction to Food Processing & Preservation',
  'FST 305': 'Food Microbiology Laboratory Practicals',
  'FST 309': 'Food Chemistry and Biochemistry',
  'FST 401': 'Food Processing Technology Practicals',
  'FST 403': 'Food Engineering Principles',
  'FST 407': 'Food Analysis and Quality Control Laboratory',
  'FST 409': 'Technology of Meat, Fish & Poultry',
  'FST 411': 'Post-Harvest Technology of Fruits & Vegetables',
  'FST 413': 'Brewing and Fermentation Technology',
  'FST 415': 'Cereal and Grain Processing Practicals',
  'FST 503': 'Advanced Food Engineering Laboratory',
  'FST 505': 'Food Packaging & Product Development Practicals',
  'FST 507': 'Sensory Evaluation of Food Products',
  'FST 509': 'Food Quality Assurance and Plant Sanitation',
  'FST 511': 'Food Laws and Regulations',
  'FST 513': 'Food Biotechnology',
  'FST 515': 'Food Process Design Practicals',
  'HSM 101': 'Introduction to Home Science & Management',
  'HSM 201': 'Family Resource Management',
  'HSM 307': 'Consumer Education & Economics',
  'HSM 313': 'Child Development and Guidance',
  'HSM 315': 'Housing & Interior Decoration',
  'HSM 317': 'Home Management Practicals',
  'HSM 321': 'Household Equipment & Maintenance',
  'HSM 323': 'Garment Construction & Tailoring',
  'HSM 325': 'Marriage and Family Relationships',
  'HSM 327': 'Community Nutrition and Health',
  'HSM 329': 'Textile Finishing and Dyeing Laboratory',
  'HSM 401': 'Advanced Family Resource Management',
  'HSM 405': 'Advanced Textile Science Practicals',
  'HSM 407': 'Textile Testing and Quality Assurance',
  'HSM 409': 'Extension Methods in Home Science',
  'HSM 413': 'Institutional Equipment Management',
  'HSM 415': 'Gender and Development in Agriculture',
  'HSM 417': 'Family Financial Planning and Counseling',
  'HSM 443': 'Gerontology and Eldercare Management',
  'CLT 101': 'Clothing Construction & Pattern Drafting',
  'CLT 105': 'Textiles & Fiber Science',
  'HTM 101': 'Introduction to Hospitality & Tourism Management',
  'HTM 103': 'Introduction to Food & Beverage Management',
  'HTM 105': 'Front Office Operations & Management',
  'HTM 107': 'Housekeeping Operations',
  'HTM 201': 'Food and Beverage Service Operations',
  'HTM 203': 'Food Preparation and Culinary Arts Practicals',
  'HTM 205': 'Hospitality Accounting',
  'HTM 207': 'Hospitality and Tourism Law',
  'HTM 209': 'Tourism Geography and Attractions',
  'HTM 211': 'Resort and Recreation Management',
  'HTM 213': 'Nutrition for Hospitality Operations',
  'HTM 307': 'Hospitality Facilities Design & Layout Practicals',
  'HTM 309': 'Event and Conference Management',
  'HTM 311': 'Bar and Beverage Management Practicals',
  'HTM 313': 'Hospitality Marketing',
  'HTM 401': 'Hospitality Strategic Management',
  'HTM 405': 'Eco-Tourism and Sustainable Hospitality',
  'HTM 407': 'Hospitality Human Resources Management',
  'HTM 411': 'Advanced Culinary Technology',
  'HTM 413': 'Hospitality Financial Management',
  'HTM 415': 'Customer Relationship Management in Tourism',
  'HTM 417': 'Aviation and Travel Agency Operations',
  'HTM 419': 'Hospitality Information Systems',
  'HTM 501': 'International Tourism Policy and Planning',
  'HTM 503': 'Advanced Hotel Operations Management',
  'HTM 505': 'Tourism Impact Assessment',
  'HTM 507': 'Gastronomy and Food Culture',
  'HTM 511': 'Casino and Gaming Management',
  'HTM 513': 'Hospitality Entrepreneurship',
  'HTM 515': 'Current Issues in Hospitality and Tourism',
  'NTD 101': 'Principles of Human Nutrition',
  'NTD 201': 'Introduction to Food and Nutrition',
  'NTD 203': 'Nutritional Assessment Methods',
  'NTD 213': 'Nutrition Laboratory Practicals',
  'NTD 301': 'Clinical Nutrition and Diet Therapy I',
  'NTD 305': 'Diet Therapy Laboratory Practicals',
  'NTD 307': 'Public Health Nutrition',
  'NTD 311': 'Nutritional Assessment & Surveillance Practicals',
  'NTD 401': 'Clinical Nutrition and Diet Therapy II Practicals',
  'NTD 405': 'Institutional Food Service Management',
  'NTD 411': 'Community Nutrition Programmes and Policies',
  'NTD 421': 'Nutritional Epidemiology',
  'NTD 423': 'Maternal and Child Nutrition Practicals',
  'NTD 425': 'Dietary Planning and Counseling Practicals',
  'NTD 429': 'Dietetics Internship and Clinical Case Studies',

  // Veterinary Medicine (COLVET)
  'VMD 101': 'Introduction to Veterinary Medicine & Animal Care',
  'VBA 201': 'Veterinary Gross Anatomy I (Osteology & Arthrology)',
  'VBA 203': 'Veterinary Histology and Embryology I',
  'VBA 301': 'Veterinary Gross Anatomy II (Visceral Systems)',
  'VBA 303': 'Veterinary Neuroanatomy',
  'VBB 201': 'Veterinary Biochemistry I',
  'VBB 301': 'Veterinary Clinical Biochemistry',
  'VBP 201': 'Veterinary Physiology I (Cardiovascular & Respiration)',
  'VBP 203': 'Veterinary Physiology Laboratory Practicals',
  'VBP 301': 'Veterinary Physiology II (Renal & Endocrine)',
  'VBP 303': 'Veterinary Pharmacology Practicals',
  'VBM 301': 'Veterinary Bacteriology and Mycology',
  'VCC 501': 'Veterinary Clinical Practice I (Small & Large Animals)',
  'VCC 601': 'Veterinary Clinical Practice II (Surgery & In-Patients)',
  'VCM 401': 'General Veterinary Medicine',
  'VCM 501': 'Avian Medicine and Diseases',
  'VCS 401': 'General Veterinary Surgery & Anaesthesiology',
  'VHM 201': 'Veterinary Public Health & Meat Hygiene',
  'VHM 203': 'Environmental Hygiene & Animal Health',
  'VPC 401': 'General Veterinary Pathology',
  'VPM 403': 'Veterinary Parasitology & Entomology',
  'VPR 401': 'Veterinary Theriogenology & Obstetrics',
  'VPT 401': 'Veterinary Systemic Pathology',
  'VPY 205': 'Veterinary Physiology and Animal Health',

  // Environmental Resources (COLERM)
  'FIS 101': 'Introduction to Fisheries & Aquaculture',
  'FIS 201': 'Ichthyology & Fish Anatomy',
  'FIS 301': 'Fish Hatchery Management Practicals',
  'FIS 303': 'Aquatic Ecology & Limnology',
  'FIS 305': 'Fish Nutrition & Feed Technology Practicals',
  'FIS 309': 'Fish Farming & Pond Construction',
  'FIS 311': 'Fish Gear Technology Practicals',
  'FIS 313': 'Fish Diseases, Parasitology & Health',
  'FIS 315': 'Aquaculture Practicals & Hatchery Operations',
  'FIS 405': 'Fish Processing & Post-Harvest Preservation',
  'FIS 501': 'Fish Breeding & Genetics Practicals',
  'FIS 505': 'Fish Population Dynamics & Stock Assessment',
  'FIS 507': 'Oceanography & Marine Fisheries Management',
  'FIS 509': 'Fisheries Economics, Marketing & Extension',
  'FWM 101': 'Introduction to Forestry & Wildlife Resources',
  'FWM 201': 'Principles of Silviculture & Forest Ecology',
  'FWM 203': 'Wood Anatomy and Timber Quality',
  'FWM 301': 'Forest Biometrics and Mensuration',
  'FWM 303': 'Wildlife Ecology and Management',
  'FWM 309': 'Silvicultural Systems and Nursery Techniques',
  'FWM 311': 'Agroforestry Principles and Practices',
  'FWM 313': 'Forest Protection & Fire Management',
  'FWM 315': 'Forestry Field Practicals',
  'FWM 503': 'Forest Inventory & Photogrammetry Practicals',
  'FRM 201': 'Forest Resources Economics',
  'FRM 211': 'Forest Harvesting & Logging Systems',
  'FRM 315': 'Forest Resources Management Practicals',
  'FRM 501': 'Wildlife Capture and Management Techniques',
  'FRM 503': 'Ecotourism and Protected Area Management',
  'FRM 507': 'Forest Genetic Resources and Tree Improvement',
  'FRM 509': 'Forest Policy, Law and Administration',
  'FRM 511': 'Environmental Impact Assessment in Forestry',
  'FRM 515': 'Wood Processing and Industry Management',
  'FWP 400': 'Wood Chemistry and Polymer Technology',
  'EMT 101': 'Introduction to Environmental Science',
  'EMT 201': 'Principles of Environmental Pollution',
  'EMT 203': 'Environmental Chemistry I',
  'EMT 205': 'Atmospheric Pollution and Climatology',
  'EMT 307': 'Environmental Sampling & Lab Analysis I',
  'EMT 401': 'Hazardous Waste Management & Treatment',
  'EMT 403': 'Environmental Toxicology Principles',
  'EMT 407': 'Environmental Law, Standards & Compliance',
  'EMT 409': 'Environmental Bio-Monitoring Practicals',
  'EMT 411': 'Water Pollution Analysis & Lab Practicals',
  'EMT 413': 'Soil Pollution and Bioremediation Practicals',
  'EMT 425': 'Noise Pollution and Industrial Ergonomics',
  'EMT 427': 'Environmental Health and Occupational Safety',
  'EMT 429': 'Disaster Management and Emergency Planning',
  'EMT 505': 'Environmental Impact Assessment Practicals',
  'EMT 509': 'Global Environmental Issues & Climate Change',
  'EMT 515': 'Remote Sensing & GIS for Environmental Monitoring',
  'EMT 517': 'Petroleum Pollution and Offshore Monitoring',
  'EMT 521': 'Urbanization, Sanitation and Environmental Ethics',
  'WMA 101': 'Introductory Meteorology & Hydrology',
  'WMA 201': 'Principles of Climatology',
  'WMA 307': 'Hydrometric Measurements & Surface Runoff',
  'WMA 309': 'Water Quality Analysis Laboratory Practicals',
  'WMA 313': 'Groundwater Hydrology & Well Drilling',
  'WMA 401': 'Agricultural Meteorology & Microclimate',
  'WMA 403': 'Agrometeorological Instrumentation Practicals',
  'WMA 411': 'Water Resource Systems Modeling Practicals',
  'WMA 413': 'Hydrological Design & Flood Control Practicals',
  'WMA 415': 'Agrometeorological Data Processing Practicals',
  'WMA 425': 'Drought, Desertification & Water Conservation',
  'WMA 501': 'Advanced Hydrological Modeling Practicals',
  'WMA 509': 'Integrated Watershed Management',
  'WMA 511': 'Irrigation Scheduling and Water Law',
  'HWM 101': 'Introduction to Hydrology & Water Resources',
  'HWM 201': 'Fluid Mechanics for Water Engineering',
  'HWM 203': 'Surface Water Hydrology',
  'HWM 205': 'Hydrological Data Analysis',
  'WSH 203': 'Soil and Water Conservation Principles',
  'WSH 205': 'Watershed Management Techniques',
  'WSH 209': 'Applied Fluvial Geomorphology',
  'WSH 211': 'Water Harvesting and Storage Systems',
  'WSH 213': 'Environmental Hydrology Practicals',
  'WSH 215': 'River Basin Planning and Management',
  'WRM 503': 'Range Evaluation and Biomass Estimation Practicals',
  'WRM 505': 'Wildlife Ecology Laboratory Practicals',
  'WRM 507': 'Zoo and Game Ranching Management Practicals',
  'WRM 509': 'Ornithology and Avian Ecology Practicals',
  'WRM 511': 'Herpetology and Wildlife Health',
  'WRM 513': 'Wildlife Economics and Safari Tourism',

  // General Studies (GNS & GST)
  'GNS 101': 'Use of Library & Information Retrieval',
  'GNS 105': 'Citizenship Education & National Values',
  'GNS 107': 'Peace Studies and Conflict Resolution',
  'GNS 108': 'Social Justice and Human Rights',
  'GNS 111': 'Use of English I (Grammar & Composition)',
  'GNS 201': 'Science, Technology and Society',
  'GNS 202': 'Introduction to Philosophy and Logic',
  'GNS 203': 'African History, Culture and Civilization',
  'GST 111': 'Communication in English & Academic Writing',
  'GST 112': 'Logic, Philosophy and Human Existence',
  'GST 201': 'Entrepreneurship and Innovation',
  'GST 203': 'Leadership and Good Governance',
  'GST 312': 'Peace Building and Conflict Resolution',

  // Official Sports
  SPORTS: 'Official University Sports & Inter-Hall Games Period',
};

/**
 * Returns the human-readable full course title / meaning for any course code.
 * Handles streams (e.g. "MTS 105 (A)"), slash combined courses ("CVE 201/GET 101"),
 * practical codes ("PHS 191"), and provides discipline fallbacks for freshers.
 */
export function getCourseMeaning(courseCode: string): string {
  if (!courseCode) return 'Official University Course';
  const clean = courseCode.toUpperCase().trim();

  // 1. Direct match in verified dictionary
  if (EXTENDED_COURSE_TITLES[clean]) {
    return EXTENDED_COURSE_TITLES[clean];
  }
  if (VERIFIED_COURSE_TITLES[clean]) {
    return VERIFIED_COURSE_TITLES[clean];
  }

  // 2. Root course code match (strips stream "(A)", "[B]", trailing times)
  const root = getRootCourseCode(clean).toUpperCase().trim();
  if (EXTENDED_COURSE_TITLES[root]) {
    return EXTENDED_COURSE_TITLES[root];
  }
  if (VERIFIED_COURSE_TITLES[root]) {
    return VERIFIED_COURSE_TITLES[root];
  }

  // 3. Slash course match (e.g. "CVE 201/GET 101", "STA/STS 201")
  if (clean.includes('/')) {
    const parts = clean.split('/').map((p) => p.trim());
    const resolvedParts = parts
      .map((part) => {
        const partRoot = getRootCourseCode(part).toUpperCase().trim();
        return (
          EXTENDED_COURSE_TITLES[part] ||
          EXTENDED_COURSE_TITLES[partRoot] ||
          VERIFIED_COURSE_TITLES[part] ||
          VERIFIED_COURSE_TITLES[partRoot] ||
          null
        );
      })
      .filter(Boolean);

    if (resolvedParts.length > 0) {
      return resolvedParts.join(' / ');
    }
  }

  // 4. Practical courses check
  const isPrac =
    clean.includes('(P)') ||
    clean.includes('[P]') ||
    clean.endsWith(' P') ||
    clean.includes('LAB') ||
    root.endsWith('91') ||
    root.endsWith('07') ||
    root.endsWith('87');

  // 5. Intelligent Prefix & Level fallback
  const prefixMatch = clean.match(/^([A-Z]{2,4})/);
  const levelMatch = clean.match(/\b([1-6])\d{2}\b/);

  if (prefixMatch) {
    const pref = prefixMatch[1];
    const discipline = COURSE_PREFIX_DISCIPLINES[pref] || pref;
    const lvl = levelMatch ? `${levelMatch[1]}00-Level` : '';
    const pracLabel = isPrac ? 'Practical Laboratory' : 'Course';

    if (discipline && lvl) {
      return `${discipline} ${lvl} ${pracLabel}`;
    }
    if (discipline) {
      return `${discipline} ${pracLabel}`;
    }
  }

  return isPrac ? 'Official Practical Laboratory' : 'Official University Course';
}
